run:
  deadline: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - govet
    - golint
    - goconst
    - gocyclo
    - lll
    - maligned
    - misspell
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  lll:
    line-length: 170
  maligned:
    suggest-new: true
  misspell:
    locale: US
  unused:
    check-exported: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true
